name: VNet APK Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Build with Buildozer
        # This is the correct repo name
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable
        env:
          # Higher memory for the VNet encryption compilation
          _JAVA_OPTIONS: "-Xmx4g"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VNet-Messenger-APK
          path: bin/*.apk
